# Generated by Django 4.2.10 on 2024-02-28 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor do Registro')),
                ('dado', models.IntegerField(max_length=10, verbose_name='03')),
                ('oficial', models.BooleanField(default=False, verbose_name='Captado pela Distribuidora')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
        migrations.CreateModel(
            name='Injecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor do Registro')),
                ('dado', models.IntegerField(max_length=10, verbose_name='103')),
                ('oficial', models.BooleanField(default=False, verbose_name='Captado pela Distribuidora')),
            ],
            options={
                'verbose_name': 'Injeção',
                'verbose_name_plural': 'Injeções',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.ManyToManyField(to='gestao.consumo', verbose_name='Histórico de Consumo')),
                ('injecao', models.ManyToManyField(to='gestao.injecao', verbose_name='Histórico de Injeção')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('titular', models.CharField(max_length=100, verbose_name='Titular da Casa')),
                ('contrato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contrato com Distribuidora')),
                ('Historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.historico', verbose_name='Histórico')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
    ]
