# Generated by Django 4.2.10 on 2024-02-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor do Registro')),
                ('consumo', models.IntegerField(verbose_name='03')),
                ('injecao', models.IntegerField(verbose_name='103')),
                ('oficial', models.BooleanField(default=False, verbose_name='Captado pela Distribuidora')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.RemoveField(
            model_name='historico',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='injecao',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='Historico',
        ),
        migrations.DeleteModel(
            name='Consumo',
        ),
        migrations.DeleteModel(
            name='Historico',
        ),
        migrations.DeleteModel(
            name='Injecao',
        ),
        migrations.AddField(
            model_name='registro',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='gestao.casa', verbose_name='Casa'),
        ),
    ]
