# Generated by Django 4.2.10 on 2024-03-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_registro_remove_historico_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='capacidade_maxima',
            field=models.IntegerField(default=600, verbose_name='Capacidade Máxima de Produção Solar'),
        ),
    ]
