# Generated by Django 4.2.10 on 2024-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_usuario_options_alter_usuario_data_nasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Foto'),
        ),
    ]
